language: ruby
rvm:
- 2.1.1
bundler_args: --without kitchen_vagrant
before_install:
- echo -n $EC2_SSH_KEY_CHUNK_{0..25} >> ~/.ssh/id_ec2.base64
- cat ~/.ssh/id_ec2.base64 | tr -d ' ' | base64 --decode > ~/.ssh/id_ec2
- gem install bundler --pre
script:
- bundle exec rake travis
after_script:
- bundle exec kitchen destroy
env:
  global:
  - EC2_SSH_KEY_PATH="$HOME/.ssh/id_ec2"
  - KITCHEN_YAML=.kitchen.cloud.yml
  - secure: OyI+x1peWYMpsZV1/DXXc+IVuvefyu8Ntw76IgH7k3bPr988gs9WHCeHfm4gvky+Cz7sAPud88FQeh0iNZpWIzmA4JOtoRc8tN4NqBZ0GAR1bL4c170zpy54HwfzISnbzMxK4u4FZCYtsbHIOZa0Ndjxc1OQZJ5aK1S7zhYmXc4=
  - secure: aaWSb3zfLcTAXDNNOdLhWfOZK1rsrHGRWPhYp+IhGKEPccaZd8UutiAxz4z0kvP/1qw/t1VMuj8MCo/oWBasJ5PuYUEnrMPWLcHoRJrXMwD9wJoV+tz7b+mIoUe8acOo3bV2p0fngHu1Q7v0wSaZPodT/34caUU+LlmdMEht+Qs=
  - secure: GdKBtVTZfQm3Hq3qWOUw241Ge7oD7ZK3eAp5IlHKkP5Fcy33vfpuN8XsZ5dEFU99BgdJ0RNzQXohEQm54j8aBxtI4vDpHHpqbJkFCmp+m0SAtcEqKdsaJBnfFL9pQRqSq1yEnAEYtFceRTo4rctPDWoGeOV0RqoV0tQLngPzdFQ=
  - secure: bpNkxY+ZMo8nLjfgjUFacZ629cPB2me8+Rc2knjON71vI+8H6odptJyCgEL9OW0bxNRkNb4S7WLb+N4ef1L/s3qsKnB7PV+3ntWlqbrKlFBJ6gGSBsrzboUnEofbIvgMGftA/p4shWLqRMxC9gxA2e66C1B1QmQFosV3Y2iV7+w=
  - secure: ZqBMYFnVtTa2xwAsERdiAtc2ygjLyP6qGbvTNEGTG4tnLh0YtFAoq9xQmW2hJjArztgOQuWSzqTowPJ8QHozitZbEp7Zyj6bzjXox2gleTse5zWzUKBLus4IoT6qn4mTLyuWxrNsIx2/AUW78jgBGEIMPWsxcsbMHYXKlurk21M=
  - secure: OT0cQ5A2aU9X8icO/oFlpD6Cn4Ghb5GIhkyMgEn9LcN6oPf4gVxlAlYORvLR4752Y4PMN7B5GRiclrCrBYQ0tW+zRNAko895dFPUmmUzwc40q0bpHEdibdEA1Ljaujz8/+Ih15c+YZSzzcLvM7BcSaUo7kXjkdreHx6FJf0rUMY=
  - secure: HPPs3H+AlBWd4Kmr/bzIB3QBfT9gIV0eVdtmdUC/7c8TbVJFdRApyKIndsiMOgYK3nRn9r70Y3TVUqmp5Fk+Z2N7FNWeXNHzDqKmQ9vJq7ju4lXo3O5a0fcE9ExYUdN7qtBxocKXZ1yN6ytsjJAsJVDKKCBnb+pufzVTGdjwybM=
  - secure: FYLL9k6yjRjWuD9jX5Pgh1wt/lUGiXyoyakhOnJ81lpRZY0NG9T9RxkX6uO9mxS7b0aZGy1htXCqlEbNwePjOokJwWmleDVfoM4hjpaJ0yNoIDdm/r8k5IVoLaAqm6JxCp/qkqmmqg+ZKoefiUHjMx9UEV5W1C1kgW2JOohgl9c=
  - secure: cLZqnbjhghTUHS+uK9GQZWySq4HkcDVwPLlwTCrCnUyl7jME+luLSYuLE6d0EmCUfZxcAtHByCIOOd2kI6OhML0z+iAVLIN6VfTvm5MqHT6zKFy87Qo64TPxmSTx30pALu9bjDxiguJFoROSer4YSe+lLYz3jxQPebdSARNTcwk=
  - secure: aydP5TmGefDCv3AdfozzikbI+igQckN486wLQrS6KbdZHbXOLfCwSbsjCvHuIvYhS0VTLq2in0J5fsW+R8KMvgazz+Rowta8O4BOru+InEFjn6rDZIVcOVdUc9NuKvabMVsFSeAtnXmG6nvyiRl/aGr9u0JlU0Pt/5vldudchao=
  - secure: XcDWhA4cVU3SBpEbP4ydXC1vsNfIlwzBjB4crH7OMjuIBVaJAD9ULjmHdTPkF4dcwi6gXRubZE8xVMUoCGHrXCyfgwKBUD2/GF+jHfLWboeJ1R5nAgX92YQHylaN/ACcchPBChib8FVw+gGwzBDvPsuXANeE8lyca3ISWKskBGY=
  - secure: RjR5CZw10FIqgGy9tv9rsVOEjfc313FZKYgBy0cx6hu8G7gVVWVkyIM7AqQx/Rzhao5klK0wkAS+lrNLfTetSScv030YZvc9/FltKukck3y6Uc+gYVhdOm5TWN0Ji0rthGELErfZsms6Wc1eh9OANyUjoedFkpVmAjhEXvUlWFM=
  - secure: iA53o8tkfBsoko4X0eDsHNo07K/dRJNj2gWOIN8XKgtoxuhh6eLlj+/rNbG3lBbModd8bNHpBGdti9Y3Efj9gode+uzlc7eql38IgyoT38eT8ej7utWtB4UK5LOGXYXCvUYsmSt22lJtS0C7s4ol70/U2koRwIpFvLPAo9M0P3s=
  - secure: L0IwS2d0bW8BsMjeAy1KjY/eKhA4+FaULhsm2gHuaZROVWlFMEqTM/OJ41dBgOxzSmIspgWiWnf5dC8Y+CKA/o4U/X+b3OmIdlQOM5T+ZHFuE5ewhPfBef9al26KgRCV+syfwDMOZNpzkpuryJWY1gS8S4Vli1twOdigeLvJYhg=
  - secure: aBoMGPfFYdcNqouESdo0XltWqHA8y5lM/inu3Ol/iXiGDDkGmo8nlf1HZe0GtbZQJkqWfjG0+jOv3tnQwoA3i+aan8vpqYwSwVWXioiU1rOc821k2HCdDQV8exrG2fIFqrpDjhmACnVQQWt+oN2GnZMuUFr3TZuy1JbwRG3Yl2U=
  - secure: BZwof31b9fmNpQrTHItVjiNreRm51gyW5qtospUQiRxp+s3UsvN8HJPHG4nGUwHZvENCh2bxJr1bRfgdxa+mERCUZxQ/XAiPUKmMXFk2HvkOaxlVX9hxJ4ZTQDIuPKCTC3uhjiMg4wXaWZflS7A5ujcn8omXw0OLeIwzwCnqJvU=
  - secure: MKm3M6kQtW26U/wlu6QODn2a0sktTMjSyenK7xt0eObFqN5HTxQEFhCjwr4b7mrYSkcsaDh8m2uYTiHXaLKqDThceKHEmslwGDl3DN5BmS4zLgkXU1+Dkp67vJ8HmHTHAXbnS+kcPzdvTOLBHtQ8VGY68o80GTj+aEQRrI3kvP4=
  - secure: Ua0M2miRNUv75Y9ICRid7MSCRYKdOY1z5gO8ku5Z9y6oxv7N/3RCDOqJCG5/hGk9bC2WkFO66IjaGgi7ZpOnBaziioO0SHFu5PTuw4DgSqhZhBMSnt3+xlgs1h28PAIh46bLtD5+I2OYS5i7DA6B6kNOxNphAVG6yZJM/INBqcU=
  - secure: CSGK1AseBr3cv9f7Af5hoWLz4ViE9TBCBPYXHAMurWjx9XUhbte4Wx04HooToSVZVdCKZHBDZn/5zG8i47gyofNeHxh5FHfx8aS/91FloHmu8+pvy0hdJ4lrBYp/9AZdnOpxmjv4+kwTrOyylBUGnOMRif6LjvgnlFGW6XFo7cw=
  - secure: Y/OigUbhnh1QDxz+a11ETns0JmYfaVqfKqPQlcJ+162cTF3OxXTmEMiEn7wEYQf8qrhckHT9dAed7mhA1BA5Ij9oTjpfiGxjtedAGO59uLKLeAcLtDxrN7Ng7TqvuCfLfzJq48aRVp31wRL4fHC05aJaPbVBEvIwUIvPpP0wuS0=
  - secure: jZq83BpRUli8YxHlkudtCsjV9re8m27Rt7p/w4ERIG+WKBHY8WeB6HYqdtmI6lY9kRRehgVrIwcat+S1MNbA2OjfeJ4+8IBrt6KgIJIHYfdiw7v1JCjuMdYAIx8b3Gc6OmnFN8xKJpszdNPG6CHBQWrCOLX4hX/E0zs3/z7AvTA=
  - secure: fdo+c6KVdGWyyozONaSiE/GpLi4aK7m5hJU01cMYy+cc5GR9S7AsKcRohr7BqvUb1hASK5z/fiFMg1oK4yrInkhLyTMj1pKaERXU1+4LpM3irbqZ7C6jgft8g+AcVV2NwnXTQ5wdflny8vlZrqaka7zYpoQHk2yB/mD3AsxIGMw=
  - secure: gSodyHIh4ozbR45VqfUpzSiubLMi8COtCn82MNV3CvCVmNs2eouyLEjxi83GXmHXnt9I1Ul5U1Mwduf18q30gcwB+tO2P/oYO91xkYXhU6Gi86TFZiO0Db1zYG5RAHVtk+sXV7nUjufc/qio9yTKGBG6NvJUGuyjFyEcfm7H8Y8=
  - secure: L+HxvUwA9PWXcsLTsyDSEUqS9WOWzWtMM/xJzCd3ROOp20TRiaDixmQhFmrohIjXHLEzuwDRmFN2ZZFGtYGI6w6icLiuK6bpPrauFagoBzGlH0loV6hvYrfaW1IwG6kDDPshg3IfTSZY5CoVPRNhsSh7wnjoVKpEnLfa70FZTUw=
  - secure: QP86/CIeS51j4dvkUO/XMj1N/CHd4C04trPFvUbJfUzI4SFYakiIGVB3voKPGfOChpQ7sWF/yLPERWzYKxnKrMAU/gSN2eobScpRKlR5olBFx/51E0X/lhEj33dzoOfqOJ1VsLvV8CjTUzcBM7g8f8/JqDQx75Vl4j6TfvBxq74=
  - secure: dfPQtzKaKJYUoRTFok/oH6bBn7QEYwlrfmQFsIfG1YrrrMSx37NaHR6Fuey7AF17Yee2KRdC7hzuLuV39j98gIQazX0WcXpG6fkIhgiFZT73KWOetraZDdzdgLnhO8fM3/EHYTq2JtyGD5hbMvKK3j2STEN1bdY2XG/Lg3CDkl0=
  - secure: aU3XNyRKn07hRJc51HIiOBtFYmgfzLNvP/cwXz+5hQB2tCzXJzkZeuP3Pc5tuXZimpyrIwjy1vIx0R2WUK1nYYMhRIdJ/NgRydfx2hMp++ibWq/wJbNFnT/jmUQSRsowuD91ZJ9iTKrqZpiEVWUzcTxEFODXxB42iE0jO/Y4e2Y=
  - secure: PiJiSQSmhSVv103BHZdzYleW8sR50Go/rArJoVbUWBHmZMwj3MqbF/kego5JWGfDI/Htb8dB9C4RzCb0TS3eHs1RPZNA7VcZVE8DTuS56lWly9HFik1+8j8MLjDWh6aE10Wz7SwqBwoBFsDTC61BRiwIPaP1stucM3E2GRXI+3E=
  - secure: auKUtq22ILxn/dtZoSSXUFrkDcNiCD9a0XPETnSjRazSHlDFhTCgmW4t/94lO7n9H0zIxlKUwSnC/6tfe9NEd+6E7/IrrYo8F9h+z3Qok8aGIyyIJBclzYfBalBBQAQKB3zspDT/CYwTMUucx0wm2oTgYew2wc1FrK/uyBV0Sww=
  - secure: bWj99sOSKiiofpR/Xylo/154afm9SeGLoBgNFKMgo1prEv1v53E2e7nt53zDTWcZNEO5lSUDNPtuTU6uHWaFHYDs0KAJtn+IITEkBqhKAx+kmCAadR6AuPuO7nsbvPq6bFQ3aixlHFRYP2Nv+aMZC76ACGaYK059MGPlfGiPPgI=
  - secure: I3RRwaAmT+i7Keet6aUnpCouV1HjYxPduvaiDGIOSG5GxFhemp5sEgCs7VxxFaWvnzEonpPKPvdgWc6TJoUELwZo163GrXSxpmIpGTCuhmaa4FBCKBEwXu63rdiNXauY47re7LgUMHvzGBKK4rY9GZdqK/E3z0UTg3OP2sJPX6w=
  matrix:
  - KITCHEN_INSTANCE="default-ubuntu-1204"
notifications:
  email:
  - techops@americanhonors.org
